name = "DevEnvConfig"
uuid = "2baef489-5d3b-4196-bdcc-c190e0714a0d"
authors = ["ylvain <ylvain.dev@ethics-gradient.org> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
PkgTemplates = "0.7"
julia = "1.6"
