
name: Documenter
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using <<&PKG>>
            DocMeta.setdocmeta!(<<&PKG>>, :DocTestSetup, :(using <<&PKG>>); recursive=true)
            doctest(<<&PKG>>)'
      - run: julia --project=docs docs/make.jl
        env:
          JULIA_PKG_SERVER: ""
          <<#LOCAL_DOC>>
          # The documentation will be deployed into the package repo.
          # There is no access right to add to this repo.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          <</LOCAL_DOC>>
          <<^LOCAL_DOC>>
          # The documentation will be deployed into another repo.
          # You must add a Secret named DOCUMENTER_KEY to the package repo
          # in order to allow write access to the target deployment repo
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}          
          <</LOCAL_DOC>>